CREATE TABLE IF NOT EXISTS SECRET (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    SECRET_GROUP_ID INT REFERENCES SECRET_GROUP(ID) NOT NULL,
    STR_VALUE TEXT,
    FILE_URL TEXT,
    UNIQUE(NAME, SECRET_GROUP_ID),
    CHECK (STR_VALUE IS NOT NULL OR FILE_URL IS NOT NULL)
);
